name: CI

on:
  push:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            bin: mycampus-calendar-rs

          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            bin: mycampus-calendar-rs

          - os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: mycampus-calendar-rs.exe

          - os: macos-latest
            target: x86_64-apple-darwin
            bin: mycampus-calendar-rs

          - os: macos-latest
            target: aarch64-apple-darwin
            bin: mycampus-calendar-rs

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2

      - name: Build
        uses: houseabsolute/actions-rust-cross@v0.0.14
        with:
          target: ${{ matrix.target }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/${{ matrix.bin }}
